### ISSUE TITLE
"butterfly" crossover in railroad diagrams

### ISSUE THREAD

**Issue by zygoloid** [tabatkins/bikeshed#1184]
Suppose we want to describe a grammar that recognizes an alternating sequence of *identifier*s and `*`s (describing a glob pattern). The natural way to render this in a railroad diagram would be to have two nodes, with the entry path going to both, the exit path coming from both, and each connected to the other.

(Can provide diagram if the above is not sufficient.) There appears to be no way to represent this in bikeshed's railroad diagram language without significant node duplication. Here a couple of bad ways of expressing this:

```
<pre class="railroad">
Or:
    Seq:
        OneOrMore:
            N: identifier
            T: *
        Opt:
            T: *
    Seq:
        OneOrMore:
            T: *
            N: identifier
        Opt:
            N: identifier
</pre>
```

```
<pre class="railroad">
Or:
    Seq:
        Opt:
            T: *
        OneOrMore:
            N: identifier
            T: *
        Opt:
            T: *
    T: *
</pre>
```
