### ISSUE TITLE
Highlight same-algorithm instances of a clicked <var>

### ISSUE THREAD

**Issue by tabatkins** [tabatkins/bikeshed#1236]
From an email about an upcoming feature in ReSpec:

>  `var` element highlighting: allowing you to click on one or more
`var` elements in a spec's section or algorithm, to see where a
variable is being used. I'm personally really excited about this
feature. As it makes it much easier to visually understand complex
spec algorithms.

This sounds very reasonable to do in Bikeshed.

**Comment by domenic** [comment]
This is also already present in Ecmarkup FWIW

**Comment by tabatkins** [comment]
Ooh, example of a spec using it? Might as well copy the styling hooks.

**Comment by domenic** [comment]
https://tc39.github.io/ecma262/ e.g. click "cp" in https://tc39.github.io/ecma262/#sec-utf16encoding

**Comment by tabatkins** [comment]
Relevant styles:

```css
var.referenced {
    background-color: #ffff33;
}

var {
    color: #2aa198;
    transition: background-color 0.25s ease;
    cursor: pointer;
}
```
