### ISSUE TITLE
Bikeshed support for GitHub Actions & listing in that marketplace?

### ISSUE THREAD

**Issue by hober** [tabatkins/bikeshed#1688]
Lots of folks roll their own "use Bikeshed to publish to their `gh-pages` branch on every push to `master`" stuff with Travis-CI. It'd be great if they could just click a few times to get it up and running with GitHub Actions & not have jump through so many hoops.

https://github.com/marketplace?type=actions&query=bikeshed

**Comment by hober** [comment]
Concretely, it would be nice to be able to collapse L13–19 of
https://github.com/w3ctag/security-questionnaire/blob/master/.github/workflows/deploy.yml#L13

to something simple like

```yaml
    - uses: tabatkins/bikeshed@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
```
