### ISSUE TITLE
fix railroad diagram vertical alignment issue.

### ISSUE THREAD

**Issue by rubys** [tabatkins/bikeshed#282]
Live example: http://intertwingly.net/projects/pegurl/url.html#host

Input used to reproduce the problem:

```
<pre class=railroad>
Choice:
  Sequence:
    T: [
    N: ipv6addr
    T: ]
  Sequence:
    N: ipv4addr
  ZeroOrMore:
    T: any except [:/\\?#]
</pre>
```
